// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vifdzquawlhnhfindcyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpZmR6cXVhd2xobmhmaW5kY3l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczOTkxMzcsImV4cCI6MjA1Mjk3NTEzN30.JlFE60c7MDf6qYeDCm9Tt3Vg_i_8pVCE9WdHEwPdqwI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);